name: nn-tpp
dependencies:
  - python=3.7
  - ipykernel
  - pip
  - pip:
    - wheel
    - numpy==1.19
    - tensorflow==2.1
    - scipy==1.4.1
    - matplotlib
    - pandas
    - protobuf<=3.20.*
    #- jupyter